version: '3.1'

services:
#  mysqldb:
#    restart: always
#    container_name: mysqldb
#    image: mysql:5.6
#    environment:
#      - MYSQL_ROOT_PASSWORD= rootdockerdb
#      - MYSQL_USER= root
#      - MYSQL_DATABASE= sondas
#    ports:
#      - 3308:3308


  explorando-app:
    restart: on-failure
    build: ./
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=rootdockerdb
      - DATABASE_NAME=sondas
      - DATABASE_PORT=3308