INSERT INTO SONDAS(NOME,COORDENADAX,COORDENADAY,DIRECAO,INSTRUCOES) VALUES('sonda1',1,2,'N','LMLMLMLMM');
INSERT INTO SONDAS(NOME,COORDENADAX,COORDENADAY,DIRECAO,INSTRUCOES) VALUES('sonda2',3,3,'E','MMRMMRMRRM');
